title: Sora LEE
description: Data Scientist
site_title: '@sora - Sora LEE'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: solalala-12
email: charmingsora12@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 