title: Abhishek Nagekar
description: Web & Security Engineer
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: solalala-12
blog_url: https://www.nagekar.com
email: charmingsora12@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 